server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          #github:
          #  clientId: ${GITHUB_CLIENT_ID}
          #  clientSecret: ${GITHUB_CLIENT_SECRET}

          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}